window:
  padding:
    x: 1
    y: 1

  decorations: none

  opacity: .75

  dynamic_title: true

font:
  size: 13.0

  normal:
    family: Hasklig
    style: Regular

  bold:
    family: Hasklig
    style: Bold

  builtin_box_drawing: true

shell:
  program: /bin/zsh

key_bindings:
  - { key: PageUp,    mods: Shift,   mode: ~Alt,        action: ScrollPageUp   }
  - { key: PageDown,  mods: Shift,   mode: ~Alt,        action: ScrollPageDown }

