[font]
builtin_box_drawing = true
size = 13.0

[font.bold]
family = "Hasklig"
style = "Bold"

[font.normal]
family = "Hasklig"
style = "Regular"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[shell]
program = "/bin/zsh"

[window]
decorations = "none"
dynamic_title = true
opacity = 0.75

[window.padding]
x = 1
y = 1
